// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-mU7Z_DzXESi8VQ7FvaS9EONLUrZhZA',
    appId: '1:388888815711:web:d15896b5e81f574e0453ea',
    messagingSenderId: '388888815711',
    projectId: 'ciphered-quest-4fcd9',
    authDomain: 'ciphered-quest-4fcd9.firebaseapp.com',
    storageBucket: 'ciphered-quest-4fcd9.appspot.com',
    measurementId: 'G-4RP0SH48ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtX1WWPPE0Dz2FoF9c6I-Zow17m4igdKc',
    appId: '1:388888815711:android:e4fbe8f1640bf95e0453ea',
    messagingSenderId: '388888815711',
    projectId: 'ciphered-quest-4fcd9',
    storageBucket: 'ciphered-quest-4fcd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABrRLVJ1OjTfTCfbzg3bF_QZ-wwOX1JAQ',
    appId: '1:388888815711:ios:4023fdd8ef398bfd0453ea',
    messagingSenderId: '388888815711',
    projectId: 'ciphered-quest-4fcd9',
    storageBucket: 'ciphered-quest-4fcd9.appspot.com',
    iosBundleId: 'com.ciphered.cipheredQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABrRLVJ1OjTfTCfbzg3bF_QZ-wwOX1JAQ',
    appId: '1:388888815711:ios:4023fdd8ef398bfd0453ea',
    messagingSenderId: '388888815711',
    projectId: 'ciphered-quest-4fcd9',
    storageBucket: 'ciphered-quest-4fcd9.appspot.com',
    iosBundleId: 'com.ciphered.cipheredQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj-mU7Z_DzXESi8VQ7FvaS9EONLUrZhZA',
    appId: '1:388888815711:web:9e448a410265f2dd0453ea',
    messagingSenderId: '388888815711',
    projectId: 'ciphered-quest-4fcd9',
    authDomain: 'ciphered-quest-4fcd9.firebaseapp.com',
    storageBucket: 'ciphered-quest-4fcd9.appspot.com',
    measurementId: 'G-JV2H8QM58R',
  );
}
